# Generated by Django 5.0.6 on 2024-06-09 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('nom_complet', models.CharField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('formateur', 'Formateur'), ('cabinet', 'Cabinet'), ('desirant', 'Desirant')], max_length=10)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('statut', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('code_utilisateur', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('description', models.CharField(max_length=254)),
                ('logo', models.CharField(max_length=254)),
                ('siteweb', models.URLField(max_length=254)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(max_length=254)),
                ('profession', models.CharField(max_length=254)),
                ('niveau_etude', models.CharField(max_length=254)),
                ('duree_experience', models.IntegerField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomaineExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cabinet')),
                ('formateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('fichier', models.CharField(max_length=254)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formateur')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='app.formateur'),
        ),
        migrations.CreateModel(
            name='FormateurDomicile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=True)),
                ('formateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.formateur')),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('FormateurDomicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formateurdomicile')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_formation', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('titre', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('duree', models.CharField(max_length=254)),
                ('prix', models.IntegerField()),
                ('format', models.CharField(max_length=254)),
                ('niveau', models.CharField(max_length=254)),
                ('photo', models.CharField(max_length=254)),
                ('tags', models.CharField(max_length=254)),
                ('langue', models.CharField(max_length=254)),
                ('domaine', models.CharField(max_length=254)),
                ('attendue', models.CharField(max_length=254)),
                ('public_vise', models.CharField(max_length=254)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Criteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=254)),
                ('contenu', models.CharField(max_length=254)),
                ('date_envoie', models.DateTimeField()),
                ('statut', models.BooleanField()),
                ('destinateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinateur', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('FormateurDomicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formateurdomicile')),
            ],
        ),
        migrations.CreateModel(
            name='Objectifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=254)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=254)),
                ('nb_place_dispo', models.IntegerField()),
                ('tarif', models.IntegerField()),
                ('statut', models.BooleanField()),
                ('code_session', models.CharField(max_length=254)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('statut', models.BooleanField()),
                ('numero', models.IntegerField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_inscription', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('statut', models.BooleanField()),
                ('prenom', models.CharField(max_length=254)),
                ('nom', models.CharField(max_length=254)),
                ('genre', models.CharField(max_length=254)),
                ('telephone', models.CharField(max_length=254)),
                ('date_naissance', models.DateTimeField()),
                ('lieu_naissance', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('adresse', models.CharField(max_length=254)),
                ('universite', models.CharField(max_length=254)),
                ('specialite', models.CharField(max_length=254)),
                ('motivation', models.TextField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.CharField(max_length=254)),
                ('date_evaluation', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session')),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours', models.CharField(max_length=60)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.session')),
            ],
        ),
        migrations.CreateModel(
            name='TempsDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours', models.CharField(max_length=70)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('formateurDomicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formateurdomicile')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
