# Generated by Django 5.0.6 on 2024-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cabinet_formateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateurdomicile',
            name='statut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
