# Generated by Django 5.0.6 on 2024-06-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_formateurdomicile_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='attendue',
        ),
    ]
