# Generated by Django 5.0.6 on 2024-06-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_formation_attendue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='specialite',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='universite',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='code_session',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
