# Generated by Django 5.0.6 on 2024-06-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inscription_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
