# Generated by Django 5.0.6 on 2024-06-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_message_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type',
            field=models.CharField(choices=[('formateur', 'Formateur'), ('cabinet', 'Cabinet'), ('desirant', 'Desirant'), ('admin', 'admin')], max_length=10),
        ),
    ]
