# Generated by Django 5.0.6 on 2024-06-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_nomcomplet_alter_message_destinateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='logo',
        ),
        migrations.AlterField(
            model_name='annee',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annee', to='app.formation'),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendriers', to='app.session'),
        ),
        migrations.AlterField(
            model_name='criteres',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='app.formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objectifs',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='app.formation'),
        ),
        migrations.AlterField(
            model_name='prerequis',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis', to='app.formation'),
        ),
    ]
