# Generated by Django 5.0.6 on 2024-06-19 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_formation_duree_remove_formation_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='app.formateur'),
        ),
    ]
